config = dict(
    APP_VERSION=0.95,
    APP_NEW_VERSION_URL="https://raw.githubusercontent.com/PW-Sat2/HAM-desktop-application/master/current_version.py",
    ZMQ_TARGET='localhost',
    ZMQ_PORT=7001,
    CLOUD_URL='http://radio.pw-sat.pl',
    PING_URL='radio.pw-sat.pl',
    CREDENTIALS_FILE='credentials.json',
    HELP_ACCOUNT='https://github.com/PW-Sat2/HAMRadio/wiki/Credentials-loading/',
    HELP_SOURCE='https://github.com/PW-Sat2/HAMRadio/wiki/Signal-source/',
    HELP_DEMODULATOR='https://github.com/PW-Sat2/HAMRadio/wiki/Demodulator-decoder/',
    HELP_UPLOAD='https://github.com/PW-Sat2/HAMRadio/wiki/Cloud-uploader/',
    HELP_WELCOME_STEP_1='https://github.com/PW-Sat2/HAMRadio/wiki/Signal-source/',
    HELP_WELCOME_STEP_2='https://github.com/PW-Sat2/HAMRadio/wiki/Demodulator-decoder/',
    HELP_WELCOME_STEP_3='https://github.com/PW-Sat2/HAMRadio/wiki/Cloud-uploader/',
    DEFAULT_SAVE_DIR='saved_frames/',
    IQ_SOURCE=0,
    GRC_BINARY='grc_windows/grc_part.exe'  # for Windows build
)
